CREATE DATABASE TesteVaga2RP;
GO

USE TesteVaga2RP;
GO

CREATE TABLE TipoUsuario(
	idTipoUsuario SMALLINT PRIMARY KEY IDENTITY,
	tituloTipoUsuario VARCHAR(50) NOT NULL
);
GO

CREATE TABLE USUARIO(
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TipoUsuario(idTipoUsuario),
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(256) UNIQUE NOT NULL,
	senha VARCHAR(256) NOT NULL,
	userStatus BIT NOT NULL
);
GO